name: Power BI CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest
    strategy:
      matrix:
        env: [dev, uat, prod]
    environment: ${{ matrix.env }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Power BI PowerShell modules
        shell: pwsh
        run: |
          Install-Module -Name MicrosoftPowerBIMgmt -Force -AllowClobber -Scope CurrentUser
          Import-Module MicrosoftPowerBIMgmt

      - name: Authenticate with Power BI
        shell: pwsh
        run: |
          $secureSecret = ConvertTo-SecureString "${{ secrets.AZURE_CLIENT_SECRET }}" -AsPlainText -Force
          $credential = New-Object System.Management.Automation.PSCredential ("${{ secrets.AZURE_CLIENT_ID }}", $secureSecret)
          Connect-PowerBIServiceAccount -ServicePrincipal -Credential $credential -Tenant "${{ secrets.AZURE_TENANT_ID }}"

      - name: Deploy PBIX to ${{ matrix.env }}
        shell: pwsh
        run: |
          ./deploy.ps1 `
            -WorkspaceId "${{ secrets.PBI_WORKSPACE_ID }}" `
            -Environment "${{ matrix.env }}"
