name: Power BI CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy-dev:
    runs-on: windows-latest
    environment: dev
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Power BI PowerShell modules
        shell: pwsh
        run: |
          Install-Module -Name MicrosoftPowerBIMgmt -Force -AllowClobber -Scope CurrentUser
          Import-Module MicrosoftPowerBIMgmt
          Import-Module MicrosoftPowerBIMgmt.Profile
          Import-Module MicrosoftPowerBIMgmt.Reports
          Import-Module MicrosoftPowerBIMgmt.Workspaces  

      - name: Deploy PBIX to Dev
        shell: pwsh
        run: |
          ./deploy.ps1 `
            -WorkspaceId "${{ secrets.PBI_WORKSPACE_DEV }}" `
            -TenantId "${{ secrets.AZURE_TENANT_ID }}" `
            -ClientId "${{ secrets.AZURE_CLIENT_ID }}" `
            -ClientSecret "${{ secrets.AZURE_CLIENT_SECRET }}"

  deploy-uat:
    needs: deploy-dev
    runs-on: windows-latest
    environment: uat
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Power BI PowerShell modules
        shell: pwsh
        run: |
          Install-Module -Name MicrosoftPowerBIMgmt -Force -AllowClobber -Scope CurrentUser
          Import-Module MicrosoftPowerBIMgmt
          Import-Module MicrosoftPowerBIMgmt.Profile
          Import-Module MicrosoftPowerBIMgmt.Reports
          Import-Module MicrosoftPowerBIMgmt.Workspaces  

      - name: Deploy PBIX to UAT
        shell: pwsh
        run: |
          ./deploy.ps1 `
            -WorkspaceId "${{ secrets.PBI_WORKSPACE_UAT }}" `
            -TenantId "${{ secrets.AZURE_TENANT_ID }}" `
            -ClientId "${{ secrets.AZURE_CLIENT_ID }}" `
            -ClientSecret "${{ secrets.AZURE_CLIENT_SECRET }}"

  deploy-prod:
    needs: deploy-uat
    runs-on: windows-latest
    environment: prod
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Power BI PowerShell modules
        shell: pwsh
        run: |
          Install-Module -Name MicrosoftPowerBIMgmt -Force -AllowClobber -Scope CurrentUser
          Import-Module MicrosoftPowerBIMgmt
          Import-Module MicrosoftPowerBIMgmt.Profile
          Import-Module MicrosoftPowerBIMgmt.Reports
          Import-Module MicrosoftPowerBIMgmt.Workspaces  

      - name: Deploy PBIX to Prod
        shell: pwsh
        run: |
          ./deploy.ps1 `
            -WorkspaceId "${{ secrets.PBI_WORKSPACE_PROD }}" `
            -TenantId "${{ secrets.AZURE_TENANT_ID }}" `
            -ClientId "${{ secrets.AZURE_CLIENT_ID }}" `
            -ClientSecret "${{ secrets.AZURE_CLIENT_SECRET }}"
