name: Power BI CI/CD Pipeline

on:
  push:
    branches:
      - main   # Trigger when code is merged to main

jobs:
  deploy-dev:
    name: Deploy to Dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup PowerShell
        uses: actions/setup-powershell@v2

      - name: Deploy PBIX to Dev
        run: pwsh ./deploy.ps1 -WorkspaceId ${{ secrets.PBI_WORKSPACE_DEV }}
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

  deploy-uat:
    name: Deploy to UAT
    needs: deploy-dev
    runs-on: ubuntu-latest
    environment:
      name: uat
      url: https://app.powerbi.com/groups/${{ secrets.PBI_WORKSPACE_UAT }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup PowerShell
        uses: actions/setup-powershell@v2

      - name: Deploy PBIX to UAT
        run: pwsh ./deploy.ps1 -WorkspaceId ${{ secrets.PBI_WORKSPACE_UAT }}
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

  deploy-prod:
    name: Deploy to Prod
    needs: deploy-uat
    runs-on: ubuntu-latest
    environment:
      name: prod
      url: https://app.powerbi.com/groups/${{ secrets.PBI_WORKSPACE_PROD }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup PowerShell
        uses: actions/setup-powershell@v2

      - name: Deploy PBIX to Prod
        run: pwsh ./deploy.ps1 -WorkspaceId ${{ secrets.PBI_WORKSPACE_PROD }}
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
