name: Power BI CI/CD

on:
  push:
    branches:
      - main

env:
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}

jobs:
  deploy-dev:
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install PowerShell Module
        run: |
          Install-Module -Name MicrosoftPowerBIMgmt -Force -Scope CurrentUser -AllowClobber

      - name: Deploy to Dev Workspace
        run: |
          pwsh ./deploy.ps1 `
            -WorkspaceId "${{ secrets.PBI_WORKSPACE_DEV }}" `
            -TenantId $env:AZURE_TENANT_ID `
            -ClientId $env:AZURE_CLIENT_ID `
            -ClientSecret $env:AZURE_CLIENT_SECRET

  deploy-uat:
    needs: deploy-dev
    runs-on: windows-latest
    environment:
      name: UAT
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install PowerShell Module
        run: |
          Install-Module -Name MicrosoftPowerBIMgmt -Force -Scope CurrentUser -AllowClobber

      - name: Deploy to UAT Workspace
        run: |
          pwsh ./deploy.ps1 `
            -WorkspaceId "${{ secrets.PBI_WORKSPACE_UAT }}" `
            -TenantId $env:AZURE_TENANT_ID `
            -ClientId $env:AZURE_CLIENT_ID `
            -ClientSecret $env:AZURE_CLIENT_SECRET

  deploy-prod:
    needs: deploy-uat
    runs-on: windows-latest
    environment:
      name: PROD
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install PowerShell Module
        run: |
          Install-Module -Name MicrosoftPowerBIMgmt -Force -Scope CurrentUser -AllowClobber

      - name: Deploy to Prod Workspace
        run: |
          pwsh ./deploy.ps1 `
            -WorkspaceId "${{ secrets.PBI_WORKSPACE_PROD }}" `
            -TenantId $env:AZURE_TENANT_ID `
            -ClientId $env:AZURE_CLIENT_ID `
            -ClientSecret $env:AZURE_CLIENT_SECRET
