name: Power BI CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest
    strategy:
      matrix:
        env: [dev, uat, prod]
    environment: ${{ matrix.env }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Power BI PowerShell modules
        shell: pwsh
        run: |
          Install-Module -Name MicrosoftPowerBIMgmt -Force -AllowClobber -Scope CurrentUser
          Import-Module MicrosoftPowerBIMgmt
          Import-Module MicrosoftPowerBIMgmt.Profile
          Import-Module MicrosoftPowerBIMgmt.Reports
          Import-Module MicrosoftPowerBIMgmt.Workspaces  

      - name: Deploy PBIX to ${{ matrix.env }}
        shell: pwsh
        run: |
          ./deploy.ps1 `
            -WorkspaceId "${{ secrets[format('PBI_WORKSPACE_{0}', matrix.env) ] }}" `
            -TenantId "${{ secrets.AZURE_TENANT_ID }}" `
            -ClientId "${{ secrets.AZURE_CLIENT_ID }}" `
            -ClientSecret "${{ secrets.AZURE_CLIENT_SECRET }}"
