name: Power BI CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy-dev:
    runs-on: windows-latest
    environment: dev
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy PBIX to Dev
        run: |
          pwsh ./deploy.ps1 `
            -ReportPath "./reports/sample-power-bi.pbix" `
            -WorkspaceId "${{ secrets.PBI_WORKSPACE_DEV }}" `
            -TenantId "${{ secrets.AZURE_TENANT_ID }}" `
            -ClientId "${{ secrets.AZURE_CLIENT_ID }}" `
            -ClientSecret "${{ secrets.AZURE_CLIENT_SECRET }}"

  deploy-uat:
    needs: deploy-dev
    runs-on: windows-latest
    environment: uat
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy PBIX to UAT
        run: |
          pwsh ./deploy.ps1 `
            -ReportPath "./reports/sample-power-bi.pbix" `
            -WorkspaceId "${{ secrets.PBI_WORKSPACE_UAT }}" `
            -TenantId "${{ secrets.AZURE_TENANT_ID }}" `
            -ClientId "${{ secrets.AZURE_CLIENT_ID }}" `
            -ClientSecret "${{ secrets.AZURE_CLIENT_SECRET }}"

  deploy-prod:
    needs: deploy-uat
    runs-on: windows-latest
    environment: prod
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy PBIX to Prod
        run: |
          pwsh ./deploy.ps1 `
            -ReportPath "./reports/sample-power-bi.pbix" `
            -WorkspaceId "${{ secrets.PBI_WORKSPACE_PROD }}" `
            -TenantId "${{ secrets.AZURE_TENANT_ID }}" `
            -ClientId "${{ secrets.AZURE_CLIENT_ID }}" `
            -ClientSecret "${{ secrets.AZURE_CLIENT_SECRET }}"
