name: Power BI CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  load-vars:
    runs-on: ubuntu-latest
    outputs:
      DEV: ${{ steps.vars.outputs.PBI_WORKSPACE_DEV }}
      UAT: ${{ steps.vars.outputs.PBI_WORKSPACE_UAT }}
      PROD: ${{ steps.vars.outputs.PBI_WORKSPACE_PROD }}
    steps:
      - uses: actions/checkout@v4

      - id: vars
        run: |
          while IFS='=' read -r key value; do
            if [[ ! "$key" =~ ^# && -n "$key" ]]; then
              echo "$key=$value" >> $GITHUB_OUTPUT
            fi
          done < variables.txt

  deploy-dev:
    needs: load-vars
    uses: ./.github/workflows/deploy-template.yml
    with:
      environment: dev
      workspace_id: ${{ needs.load-vars.outputs.DEV }}
    secrets: inherit

  deploy-uat:
    needs: [deploy-dev, load-vars]
    uses: ./.github/workflows/deploy-template.yml
    with:
      environment: uat
      workspace_id: ${{ needs.load-vars.outputs.UAT }}
    secrets: inherit

  deploy-prod:
    needs: [deploy-uat, load-vars]
    uses: ./.github/workflows/deploy-template.yml
    with:
      environment: prod
      workspace_id: ${{ needs.load-vars.outputs.PROD }}
    secrets: inherit
